name = "EntroPlots"
uuid = "742586e2-2ccd-48a5-bc1c-31de6daa8fd7"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "0.1.4"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Plots = "1.40"
Revise = "3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
